QUESTIONS = [
    {
        "query": "What are the best home bakeries in Noida?",
        "category": "local",
        "subcategory": "bakery",
        "intent": "discovery",
        "geography": "Noida",
        "commercial_intent": "high",
        "entity_type": "business",
        "difficulty": "medium",
    },
    {
        "query": "Where can I order an eggless birthday cake in Noida?",
        "category": "local",
        "subcategory": "cake",
        "intent": "transactional",
        "geography": "Noida",
        "commercial_intent": "high",
        "entity_type": "business",
        "difficulty": "medium",
    },
    {
        "query": "How much does a 1 kg custom cake usually cost in Noida?",
        "category": "local",
        "subcategory": "cake pricing",
        "intent": "commercial research",
        "geography": "Noida",
        "commercial_intent": "high",
        "entity_type": "product/service",
        "difficulty": "medium",
    },
    {
        "query": "What is the best type of cake for a child's birthday party?",
        "category": "cake",
        "subcategory": "selection",
        "intent": "informational",
        "geography": "India",
        "commercial_intent": "medium",
        "entity_type": "product",
        "difficulty": "easy",
    },
    {
        "query": "How do I make an eggless chocolate cake?",
        "category": "recipe",
        "subcategory": "eggless cake",
        "intent": "informational",
        "geography": "India",
        "commercial_intent": "low",
        "entity_type": "recipe",
        "difficulty": "easy",
    },
    {
        "query": "Why does my eggless cake sink after baking?",
        "category": "baking",
        "subcategory": "troubleshooting",
        "intent": "informational",
        "geography": "India",
        "commercial_intent": "low",
        "entity_type": "problem",
        "difficulty": "medium",
    },
    {
        "query": "What are the best online baking classes for beginners in India?",
        "category": "baking classes",
        "subcategory": "online",
        "intent": "commercial research",
        "geography": "India",
        "commercial_intent": "high",
        "entity_type": "course",
        "difficulty": "medium",
    },
    {
        "query": "How much does an online baking class usually cost in India?",
        "category": "baking classes",
        "subcategory": "pricing",
        "intent": "commercial research",
        "geography": "India",
        "commercial_intent": "high",
        "entity_type": "course",
        "difficulty": "easy",
    },
    {
        "query": "What is a good oven for home baking in India?",
        "category": "equipment",
        "subcategory": "oven",
        "intent": "commercial research",
        "geography": "India",
        "commercial_intent": "high",
        "entity_type": "product",
        "difficulty": "medium",
    },
    {
        "query": "What is better for a cake: buttercream or whipped cream?",
        "category": "cake",
        "subcategory": "frosting",
        "intent": "comparison",
        "geography": "India",
        "commercial_intent": "low",
        "entity_type": "ingredient",
        "difficulty": "easy",
    },
]